# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import ed4.models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_to_text',
            name='document',
            field=models.FileField(blank=True, upload_to=ed4.models.custom_directory_path),
        ),
        migrations.AlterField(
            model_name='word_to_text',
            name='video',
            field=models.FileField(blank=True, upload_to=ed4.models.custom_directory_path),
        ),
    ]
