# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed4', '0002_auto_20190413_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word_to_text',
            new_name='word2video',
        ),
    ]
