# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ed4.models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4', '0003_auto_20190413_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to=ed4.models.custom_directory_path)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='word2video',
        ),
        migrations.CreateModel(
            name='VidTextFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ed4.PostFile')),
                ('text', models.TextField(blank=True, max_length=2000)),
                ('video', models.FileField(blank=True, upload_to=ed4.models.custom_directory_path)),
            ],
        ),
    ]
